package scr;

public enum TCPPrefixes {
    ASSIGN_ORDER,
    GET_BOARD,
    GET_BOARD_REPLY,
    SEND_MOVE,
    SEND_MOVE_REPLY,
    CLOSE_CONNECTION,
    WAIT_FOR_OPPONENT_MOVE,
    WAIT_FOR_OPPONENT_MOVE_REPLY,
    WAIT_FOR_OPPONENT_CONNECT,
    WAIT_FOR_OPPONENT_CONNECT_REPLY,
}
