package scr;

public enum TCPPrefixes {
    ASSIGN_ORDER,
    GET_BOARD,
    GET_BOARD_REPLY,
    SEND_MOVE,
    SEND_MOVE_REPLY,
    CLOSE_CONNECTION,
    WAIT_FOR_OPPONENT,
    WAIT_FOR_OPPONENT_REPLY
}
